{"name":"Update: Failure","fullName":"TestPublicationPgRepoSuiteRunner/PublicationPgRepoSuit/TestPublicationPgRepo_UpdateFailure","status":"passed","statusDetails":{"message":"","trace":""},"start":1727679994697,"stop":1727679994697,"uuid":"8732020c-7efa-11ef-baf3-be2bab8c44a1","historyId":"c748530daa8d346074db03fbbb74e415","testCaseId":"d9c71ea48805fe7d43cd47d2585a3e1e","labels":[{"name":"language","value":"go1.23.1"},{"name":"framework","value":"Allure-Go@v0.6.0"},{"name":"host","value":"MacBook-Pro-Pavel-2.local"},{"name":"thread","value":"TestPublicationPgRepoSuiteRunner/PublicationPgRepoSuit/TestPublicationPgRepo_UpdateFailure"},{"name":"suite","value":"PublicationPgRepoSuit"},{"name":"package","value":"cookdroogers/internal/repo/pg"},{"name":"tag","value":"PublicationPgRepo"}],"steps":[{"name":"Failure","status":"passed","start":1727679994697,"stop":1727679994697,"steps":[{"name":"ASSERT: Error Is","status":"passed","start":1727679994697,"stop":1727679994697,"parameters":[{"name":"Error","value":"sql: connection is already closed: error in postgres repo"},{"name":"Target","value":"error in postgres repo"}]}]}]}