{"name":"Create: Failure","fullName":"TestReleasePgRepoSuiteRunner/ReleasePgRepoSuit/TestReleasePgRepo_CreateFailure","status":"passed","statusDetails":{"message":"","trace":""},"start":1728207864909,"stop":1728207864910,"uuid":"925be1ee-83c7-11ef-9255-be2bab8c44a2","historyId":"5283e85181480698c00561bf0a50409d","testCaseId":"4d4a13b7da2892815d7eea725a8adc91","labels":[{"name":"language","value":"go1.23.0"},{"name":"framework","value":"Allure-Go@v0.6.0"},{"name":"host","value":"MBP-Pavel-2.netis.cc"},{"name":"thread","value":"TestReleasePgRepoSuiteRunner/ReleasePgRepoSuit/TestReleasePgRepo_CreateFailure"},{"name":"suite","value":"ReleasePgRepoSuit"},{"name":"package","value":"cookdroogers/internal/repo/pg"},{"name":"tag","value":"ReleasePgRepo"}],"steps":[{"name":"Failure","status":"passed","start":1728207864909,"stop":1728207864910,"steps":[{"name":"ASSERT: Error Is","status":"passed","start":1728207864910,"stop":1728207864910,"parameters":[{"name":"Error","value":"sql: connection is already closed: error in postgres repo; transaction: rollback; call to Rollback transaction, was not expected, next expectation is: ExpectedExec =\u003e expecting Exec or ExecContext which:\n  - matches sql: 'UPDATE tracks SET release_id=$1 WHERE track_id=$2'\n  - is without arguments\n  - should return error: sql: connection is already closed"},{"name":"Target","value":"error in postgres repo"}]}]}]}