{"name":"UpdateType: Failure","fullName":"TestUserPgRepoSuiteRunner/UserPgRepoSuit/TestUserPgRepo_UpdateTypeFailure","status":"passed","statusDetails":{"message":"","trace":""},"start":1727708878270,"stop":1727708878270,"uuid":"c725b474-7f3d-11ef-89d3-be2bab8c44a1","historyId":"e631e8d28011449b4b7901b576c8049e","testCaseId":"7103cfa55d7637250dcb34ecbd988987","labels":[{"name":"language","value":"go1.23.1"},{"name":"framework","value":"Allure-Go@v0.6.0"},{"name":"host","value":"MacBook-Pro-Pavel-2.local"},{"name":"thread","value":"TestUserPgRepoSuiteRunner/UserPgRepoSuit/TestUserPgRepo_UpdateTypeFailure"},{"name":"suite","value":"UserPgRepoSuit"},{"name":"package","value":"cookdroogers/internal/repo/pg"},{"name":"tag","value":"UserPgRepo"}],"steps":[{"name":"Failure","status":"passed","start":1727708878270,"stop":1727708878270,"steps":[{"name":"ASSERT: Error Is","status":"passed","start":1727708878270,"stop":1727708878270,"parameters":[{"name":"Error","value":"call to ExecQuery 'UPDATE users SET type=$1 WHERE user_id=$2' with args [{Name: Ordinal:1 Value:2} {Name: Ordinal:2 Value:7}], was not expected, next expectation is: ExpectedQuery =\u003e expecting Query, QueryContext or QueryRow which:\n  - matches sql: 'UPDATE users SET type=$1 WHERE user_id=$2'\n  - is without arguments\n  - should return error: sql: connection is already closed: error in postgres repo"},{"name":"Target","value":"error in postgres repo"}]}]}]}