{"name":"Create: Failure","fullName":"TestManagerPgRepoSuiteRunner/ManagerPgRepoSuite/TestManagerPgRepo_CreateFailure","status":"passed","statusDetails":{"message":"","trace":""},"start":1727679710913,"stop":1727679710914,"uuid":"de0cd102-7ef9-11ef-971d-be2bab8c44a1","historyId":"093a8a0ea044fb3a4fc601976c4955a4","testCaseId":"c84196936ff421c82772ffc584b95791","labels":[{"name":"language","value":"go1.23.1"},{"name":"framework","value":"Allure-Go@v0.6.0"},{"name":"host","value":"MacBook-Pro-Pavel-2.local"},{"name":"thread","value":"TestManagerPgRepoSuiteRunner/ManagerPgRepoSuite/TestManagerPgRepo_CreateFailure"},{"name":"suite","value":"ManagerPgRepoSuite"},{"name":"package","value":"cookdroogers/internal/repo/pg"},{"name":"tag","value":"ManagerPgRepo"}],"steps":[{"name":"Failure","status":"passed","start":1727679710913,"stop":1727679710914,"steps":[{"name":"ASSERT: Error Is","status":"passed","start":1727679710914,"stop":1727679710914,"parameters":[{"name":"Error","value":"sql: connection is already closed: error in postgres repo; transaction: rollback; call to Rollback transaction, was not expected, next expectation is: ExpectedExec =\u003e expecting Exec or ExecContext which:\n  - matches sql: 'UPDATE artists SET manager_id=$1 WHERE artist_id=$2'\n  - is without arguments\n  - should return error: sql: connection is already closed"},{"name":"Target","value":"error in postgres repo"}]}]}]}