{"name":"Create: Failure","fullName":"TestReleasePgRepoSuiteRunner/ReleasePgRepoSuit/TestReleasePgRepo_CreateFailure","status":"passed","statusDetails":{"message":"","trace":""},"start":1727679710919,"stop":1727679710920,"uuid":"de0df546-7ef9-11ef-971d-be2bab8c44a1","historyId":"5283e85181480698c00561bf0a50409d","testCaseId":"4d4a13b7da2892815d7eea725a8adc91","labels":[{"name":"language","value":"go1.23.1"},{"name":"framework","value":"Allure-Go@v0.6.0"},{"name":"host","value":"MacBook-Pro-Pavel-2.local"},{"name":"thread","value":"TestReleasePgRepoSuiteRunner/ReleasePgRepoSuit/TestReleasePgRepo_CreateFailure"},{"name":"suite","value":"ReleasePgRepoSuit"},{"name":"package","value":"cookdroogers/internal/repo/pg"},{"name":"tag","value":"ReleasePgRepo"}],"steps":[{"name":"Failure","status":"passed","start":1727679710920,"stop":1727679710920,"steps":[{"name":"ASSERT: Error Is","status":"passed","start":1727679710920,"stop":1727679710920,"parameters":[{"name":"Error","value":"sql: connection is already closed: error in postgres repo; transaction: rollback; call to Rollback transaction, was not expected, next expectation is: ExpectedExec =\u003e expecting Exec or ExecContext which:\n  - matches sql: 'UPDATE tracks SET release_id=$1 WHERE track_id=$2'\n  - is without arguments\n  - should return error: sql: connection is already closed"},{"name":"Target","value":"error in postgres repo"}]}]}]}