{"name":"Create: Failure","fullName":"TestPublicationPgRepoSuiteRunner/PublicationPgRepoSuit/TestPublicationPgRepo_CreateFailure","status":"passed","statusDetails":{"message":"","trace":""},"start":1727679684338,"stop":1727679684339,"uuid":"ce36258a-7ef9-11ef-b30c-be2bab8c44a1","historyId":"a9255b9a51cb98bd12ebd8d3d567e445","testCaseId":"7dfa97f5c4965f7c962951a14277a31b","labels":[{"name":"language","value":"go1.23.1"},{"name":"framework","value":"Allure-Go@v0.6.0"},{"name":"host","value":"MacBook-Pro-Pavel-2.local"},{"name":"thread","value":"TestPublicationPgRepoSuiteRunner/PublicationPgRepoSuit/TestPublicationPgRepo_CreateFailure"},{"name":"suite","value":"PublicationPgRepoSuit"},{"name":"package","value":"cookdroogers/internal/repo/pg"},{"name":"tag","value":"PublicationPgRepo"}],"steps":[{"name":"Failure","status":"passed","start":1727679684339,"stop":1727679684339,"steps":[{"name":"ASSERT: Error Is","status":"passed","start":1727679684339,"stop":1727679684339,"parameters":[{"name":"Error","value":"sql: connection is already closed: error in postgres repo"},{"name":"Target","value":"error in postgres repo"}]}]}]}